### ISSUE TITLE
config/scaffold.yml doesn't seem to be honoring...

### ISSUE THREAD

**Issue by darron** [grimen/dry_scaffold#11]
my:

resourceful: false
shoulda: true

I've done this a couple times today to make sure - here's a gist:

http://gist.github.com/224563

If I pass it on the command line - it works just fine:

./script/generate dry_scaffold Zebra name:string about:text --skip-resourceful --shoulda

I may be doing something wrong - but I just want to:

create a rails app
add dry_scaffold
add a simple model/controller with your scaffold generator
have the basic tests pass

And I can't seem to be able to do that - like I said, I may be doing something wrong, but am not sure what.

**Comment by Jonsey** [comment]
I get a similar problem with controller test.  In the scaffold.yaml I have 

---

dry_scaffold:
  args:
    actions: index,show,new,edit,create,update,destroy
    formats: html,js
  options:
    formtastic: true
    resourceful: true
    pagination: true
    layout: false
    views: true
    helpers: true
    tests: true
    controller_tests: true
    test_unit: false
    shoulda: false
    rspec: true
    fixtures: false
    fgirl: true
    machinist: false
    object_daddy: false
dry_model:
  options:
    migration: true
    timestamps: true
    tests: true
    test_unit: false
    shoulda: false
    rspec: true
    fixtures: false
    fgirl: true
    machinist: false
    object_daddy: false

but helper test and controller test are created for test-unit

if I use the command line option --rspec then the specs are generated properly.

**Comment by grimen** [comment]
See:

http://github.com/grimen/dry_scaffold/commit/7c5a557b48d0be6937aeeb9648729f6f8c3555e1

**Comment by nonfiction** [comment]
Thanks!
