### ISSUE TITLE
Use inherited_resources paths

### ISSUE THREAD

**Issue by baldwindavid** [grimen/dry_scaffold#12]
Use collection_path, resource_path, etc. unless skipping inherited_resources.  
Also, perhaps use the longer method for creating the form tag...

```
- semantic_form_for resource, :url => edit_resource_path(resource) do |form|
```

This will allow belongs_to/polymorphic controllers without any updates to the views.

**Comment by grimen** [comment]
bugfix: Use inherited_resources paths (again). Closed by 12a6e102b00abae5a11560aa53b1922291b21d0a
