### ISSUE TITLE
Any plans for creating a similar project to support rails 3? ;)

### ISSUE THREAD

**Issue by kristianmandrup** [grimen/dry_scaffold#22]
http://blog.plataformatec.com.br/tag/thor/
http://yehudakatz.com/2008/05/12/by-thors-hammer

**Comment by grimen** [comment]
No, don't think so. I'mactually have little time for this project as may be seen by all the open tickets. The generators in Rails  are kick-ass too, so I doubt it's really needed later on when more plugins got Rails 3-style generators.

**Comment by grimen** [comment]
Closing
